const kataKorea = {
  level1: [
    {
      hangeul: "안녕하세요",
      pelafalan: "annyeonghaseyo",
      arti: "Halo",
      contohKalimat: "안녕하세요! 저는 한국에서 왔어요.",
      pelafalanKalimat: "annyeonghaseyo! Jeoneun Hangukeseo wasseoyo.",
      artiKalimat: "Halo! Saya berasal dari Korea.",
    },
    {
      hangeul: "감사합니다",
      pelafalan: "gamsahamnida",
      arti: "Terima kasih",
      contohKalimat: "감사합니다, 친절하시네요.",
      pelafalanKalimat: "gamsahamnida, chinjeolhasineyo.",
      artiKalimat: "Terima kasih, Anda sangat ramah.",
    },
    {
      hangeul: "사랑해요",
      pelafalan: "saranghaeyo",
      arti: "Aku cinta padamu",
      contohKalimat: "엄마, 사랑해요!",
      pelafalanKalimat: "eomma, saranghaeyo!",
      artiKalimat: "Ibu, aku mencintaimu!",
    },
    {
      hangeul: "미안해요",
      pelafalan: "mianhaeyo",
      arti: "Maaf",
      contohKalimat: "미안해요, 제가 실수했어요.",
      pelafalanKalimat: "mianhaeyo, jega silsuhaesseoyo.",
      artiKalimat: "Maaf, saya membuat kesalahan.",
    },
    {
      hangeul: "네",
      pelafalan: "ne",
      arti: "Ya",
      contohKalimat: "네, 알겠습니다.",
      pelafalanKalimat: "ne, algesseumnida.",
      artiKalimat: "Ya, saya mengerti.",
    },
    {
      hangeul: "아니요",
      pelafalan: "aniyo",
      arti: "Tidak",
      contohKalimat: "아니요, 그것은 틀렸어요.",
      pelafalanKalimat: "aniyo, geugeoseun teullyeosseoyo.",
      artiKalimat: "Tidak, itu salah.",
    },
    {
      hangeul: "어떻게요",
      pelafalan: "eotteokeyo",
      arti: "Bagaimana?",
      contohKalimat: "오늘 저녁에 뭐 해요? 어떻게요?",
      pelafalanKalimat: "oneul jeonyeoge mwo haeyo? eotteokeyo?",
      artiKalimat: "Apa yang akan kita lakukan malam ini? Bagaimana?",
    },
    {
      hangeul: "뭐",
      pelafalan: "mwo",
      arti: "Apa?",
      contohKalimat: "뭐? 이해하지 못해요.",
      pelafalanKalimat: "mwo? ihaehaji mothaeyo.",
      artiKalimat: "Apa? Saya tidak mengerti.",
    },
    {
      hangeul: "이해해요",
      pelafalan: "ihaehaeyo",
      arti: "Saya mengerti",
      contohKalimat: "네 말을 이해해요.",
      pelafalanKalimat: "ne mareul ihaehaeyo.",
      artiKalimat: "Saya mengerti apa yang kamu katakan.",
    },
    {
      hangeul: "좋아요",
      pelafalan: "joayo",
      arti: "Bagus / Suka",
      contohKalimat: "이 음식 정말 맛있어요. 많이 좋아요.",
      pelafalanKalimat: "i eumsik jeongmal masisseoyo. manhi joayo.",
      artiKalimat: "Makanan ini sangat lezat. Saya sangat menyukainya.",
    },
    {
      hangeul: "싫어요",
      pelafalan: "sireoyo",
      arti: "Tidak suka",
      contohKalimat: "저는 고양이를 좋아해요, 하지만 개는 싫어요.",
      pelafalanKalimat: "jeoneun goyangireul joahaeyo, hajiman gaeneun sireoyo.",
      artiKalimat: "Saya suka kucing, tapi saya tidak suka anjing.",
    },
    {
      hangeul: "도와주세요",
      pelafalan: "dowajuseyo",
      arti: "Tolong bantu saya",
      contohKalimat: "제가 방금 지갑을 잃어버렸어요. 도와주세요!",
      pelafalanKalimat: "jega banggeum jigaubeoryeosseoyo. dowajuseyo!",
      artiKalimat: "Saya baru saja kehilangan dompet saya. Tolong bantu saya!",
    },
    {
      hangeul: "물",
      pelafalan: "mul",
      arti: "Air",
      contohKalimat: "목이 마르네요. 물 주세요.",
      pelafalanKalimat: "mogi mareuneyo. mul juseyo.",
      artiKalimat: "Saya haus. Tolong berikan air.",
    },
    {
      hangeul: "음식",
      pelafalan: "eumsik",
      arti: "Makanan",
      contohKalimat: "한국 음식은 매우 맛있어요.",
      pelafalanKalimat: "Hanguk eumsikeun maeu masisseoyo.",
      artiKalimat: "Makanan Korea sangat lezat.",
    },
    {
      hangeul: "학교",
      pelafalan: "hakgyo",
      arti: "Sekolah",
      contohKalimat: "저는 학교에 갑니다.",
      pelafalanKalimat: "jeoneun hakgyoe gamnida.",
      artiKalimat: "Saya pergi ke sekolah.",
    },
    {
      hangeul: "집",
      pelafalan: "jip",
      arti: "Rumah",
      contohKalimat: "오늘은 집에서 쉬겠어요.",
      pelafalanKalimat: "oneureun jibeseo swigesseoyo.",
      artiKalimat: "Hari ini saya akan istirahat di rumah.",
    },
    {
      hangeul: "친구",
      pelafalan: "chingu",
      arti: "Teman",
      contohKalimat: "저의 친구들과 함께 파티에 가요.",
      pelafalanKalimat: "jeoui chingudeulgwa hamkke patie gayo.",
      artiKalimat: "Saya akan pergi ke pesta bersama teman-teman saya.",
    },
    {
      hangeul: "가방",
      pelafalan: "gabang",
      arti: "Tas",
      contohKalimat: "가방을 잊어버렸어요. 집에 다시 가져와야 해요.",
      pelafalanKalimat: "gabangeul ijeobeoryeosseoyo. jibe dasi gajyeowaya haeyo.",
      artiKalimat: "Saya lupa tas saya. Saya harus mengambilnya kembali di rumah.",
    },
    {
      hangeul: "기차",
      pelafalan: "gicha",
      arti: "Kereta api",
      contohKalimat: "서울로 가는 기차가 몇 시에 있어요?",
      pelafalanKalimat: "Seoulloro ganeun gichaga myeot sie isseoyo?",
      artiKalimat: "Pukul berapa kereta menuju Seoul?",
    },
    {
      hangeul: "버스",
      pelafalan: "beoseu",
      arti: "Bus",
      contohKalimat: "이 버스는 시내를 다니나요?",
      pelafalanKalimat: "i beoseuneun sinaereul daninayo?",
      artiKalimat: "Apakah bus ini beroperasi di kota?",
    },
  ],

  level2: [
    {
      hangeul: "먹다",
      pelafalan: "meokda",
      arti: "Makan",
      contohKalimat: "저는 밥을 먹었어요.",
      pelafalanKalimat: "jeoneun bapeul meogeosseoyo.",
      artiKalimat: "Saya makan nasi.",
    },
    {
      hangeul: "마시다",
      pelafalan: "masida",
      arti: "Minum",
      contohKalimat: "물을 한잔 마셨어요.",
      pelafalanKalimat: "mureul hanjan masyeosseoyo.",
      artiKalimat: "Saya minum segelas air.",
    },
    {
      hangeul: "자다",
      pelafalan: "jada",
      arti: "Tidur",
      contohKalimat: "어제 밤에 잘 잤어요.",
      pelafalanKalimat: "eoje bame jal jasseoyo.",
      artiKalimat: "Saya tidur nyenyak semalam.",
    },
    {
      hangeul: "일하다",
      pelafalan: "ilhada",
      arti: "Bekerja",
      contohKalimat: "저는 회사에서 일해요.",
      pelafalanKalimat: "jeoneun hoesaeseo ilhaeyo.",
      artiKalimat: "Saya bekerja di perusahaan.",
    },
    {
      hangeul: "공부하다",
      pelafalan: "gongbuhada",
      arti: "Belajar",
      contohKalimat: "저는 한국어를 공부하고 있어요.",
      pelafalanKalimat: "jeoneun hangugeo-reul gongbu-hago isseoyo.",
      artiKalimat: "Saya sedang belajar bahasa Korea.",
    },
    {
      hangeul: "보다",
      pelafalan: "boda",
      arti: "Melihat / Menonton",
      contohKalimat: "영화를 보러 갈까요?",
      pelafalanKalimat: "yeonghwa-reul boreo galkkayo?",
      artiKalimat: "Mau pergi nonton film?",
    },
    {
      hangeul: "듣다",
      pelafalan: "deutda",
      arti: "Mendengar / Mendengarkan",
      contohKalimat: "음악을 듣는 것을 좋아해요.",
      pelafalanKalimat: "eumak-eul deutneun geos-eul joh-ahae-yo.",
      artiKalimat: "Saya suka mendengarkan musik.",
    },
    {
      hangeul: "말하다",
      pelafalan: "malhada",
      arti: "Berbicara / Berkata",
      contohKalimat: "한국어로 말해주세요.",
      pelafalanKalimat: "hangugeo-lo malhaejuseyo.",
      artiKalimat: "Tolong berbicara dalam bahasa Korea.",
    },
    {
      hangeul: "가다",
      pelafalan: "gada",
      arti: "Pergi",
      contohKalimat: "저는 학교에 가요.",
      pelafalanKalimat: "jeoneun hakkyo-e gayo.",
      artiKalimat: "Saya pergi ke sekolah.",
    },
    {
      hangeul: "오다",
      pelafalan: "oda",
      arti: "Datang",
      contohKalimat: "친구들이 내일 올 거예요.",
      pelafalanKalimat: "chingudeul-i naeil ol geoyeyo.",
      artiKalimat: "Teman-teman akan datang besok.",
    },
    {
      hangeul: "도착하다",
      pelafalan: "dochakhada",
      arti: "Tiba",
      contohKalimat: "비행기가 서울에 도착했어요.",
      pelafalanKalimat: "bihaeng-giga seoul-e dochakhaesseoyo.",
      artiKalimat: "Pesawat sudah tiba di Seoul.",
    },
    {
      hangeul: "사진",
      pelafalan: "sajin",
      arti: "Foto",
      contohKalimat: "이 사진은 아름답네요.",
      pelafalanKalimat: "i sajin-eun aleumdapneyo.",
      artiKalimat: "Foto ini indah.",
    },
    {
      hangeul: "책",
      pelafalan: "chaek",
      arti: "Buku",
      contohKalimat: "좋아하는 책을 추천해주세요.",
      pelafalanKalimat: "joh-ahaneun chaeg-eul chucheonhaejuseyo.",
      artiKalimat: "Tolong rekomendasikan buku yang bagus.",
    },
    {
      hangeul: "시간",
      pelafalan: "sigan",
      arti: "Waktu",
      contohKalimat: "지금 몇 시예요?",
      pelafalanKalimat: "jigeum myeot siyeyo?",
      artiKalimat: "Sekarang jam berapa?",
    },
    {
      hangeul: "날씨",
      pelafalan: "nalssi",
      arti: "Cuaca",
      contohKalimat: "오늘 날씨가 좋네요.",
      pelafalanKalimat: "oneul nalssiga johneyo.",
      artiKalimat: "Cuaca hari ini bagus.",
    },
    {
      hangeul: "전화",
      pelafalan: "jeonhwa",
      arti: "Telepon",
      contohKalimat: "친구에게 전화를 걸었어요.",
      pelafalanKalimat: "chingu-ege jeonhwa-reul geol-eosseoyo.",
      artiKalimat: "Saya menelepon teman.",
    },
    {
      hangeul: "여행",
      pelafalan: "yeohaeng",
      arti: "Perjalanan / Wisata",
      contohKalimat: "다음 달에 해외로 여행할 거예요.",
      pelafalanKalimat: "da-eum dal-e haeo-lo yeohaenghal geoyeyo.",
      artiKalimat: "Bulan depan saya akan berwisata ke luar negeri.",
    },
    {
      hangeul: "노래",
      pelafalan: "nolae",
      arti: "Lagu",
      contohKalimat: "이 노래를 들어봤어요.",
      pelafalanKalimat: "i nolaereul deul-eobwass-eoyo.",
      artiKalimat: "Saya sudah mendengar lagu ini.",
    },
    {
      hangeul: "영화",
      pelafalan: "yeonghwa",
      arti: "Film",
      contohKalimat: "저는 영화를 보는 것을 좋아해요.",
      pelafalanKalimat: "jeoneun yeonghwa-reul boneun geos-eul joh-ahae-yo.",
      artiKalimat: "Saya suka menonton film.",
    },
    {
      hangeul: "공원",
      pelafalan: "gongwon",
      arti: "Taman",
      contohKalimat: "주말에 공원에 가는 게 좋아요.",
      pelafalanKalimat: "jumal-e gong-won-e ganeun ge joh-ah-yo.",
      artiKalimat: "Pergi ke taman di akhir pekan itu bagus.",
    },
  ],
};
