const kataKorea = {
  level1: [
    {
      hangeul: "미리",
      pelafalan: "miri",
      arti: "Sebelumnya",
      contohKalimat: "미리 준비해 놓았어요.",
      pelafalanKalimat: "Miri junbihae noass-eoyo.",
      artiKalimat: "Sudah saya siapkan sebelumnya.",
    },
    {
      hangeul: "감사합니다",
      pelafalan: "gamsahamnida",
      arti: "Terima kasih",
      contohKalimat: "감사합니다, 친절하시네요.",
      pelafalanKalimat: "Gamsahamnida, chinjeolhasineyo.",
      artiKalimat: "Terima kasih, Anda sangat ramah.",
    },
    {
      hangeul: "물고기",
      pelafalan: "mulgogi",
      arti: "Ikan",
      contohKalimat: "저는 물고기를 좋아해요.",
      pelafalanKalimat: "Jeoneun mulgogileul joh-ahaeoyo.",
      artiKalimat: "Saya menyukai ikan.",
    },
    {
      hangeul: "안녕하세요",
      pelafalan: "annyeonghaseyo",
      arti: "Halo",
      contohKalimat: "안녕하세요! 만나서 반가워요.",
      pelafalanKalimat: "Annyeonghaseyo! Mannaseo bangawoyo.",
      artiKalimat: "Halo! Senang bertemu dengan Anda.",
    },
    {
      hangeul: "좋아요",
      pelafalan: "joh-ayo",
      arti: "Suka",
      contohKalimat: "나는 이 노래가 좋아요.",
      pelafalanKalimat: "Naneun i nolaega joh-ayo.",
      artiKalimat: "Saya menyukai lagu ini.",
    },
    {
      hangeul: "싫어요",
      pelafalan: "silaeyo",
      arti: "Tidak suka",
      contohKalimat: "나는 이 음식을 싫어해요.",
      pelafalanKalimat: "Naneun i eumsig-eul silh-eohae-yo.",
      artiKalimat: "Saya tidak suka makanan ini.",
    },
    {
      hangeul: "사랑해요",
      pelafalan: "salanghaeyo",
      arti: "Aku mencintaimu",
      contohKalimat: "나는 너를 사랑해요.",
      pelafalanKalimat: "Naneun neoleul salanghaeyo.",
      artiKalimat: "Aku mencintaimu.",
    },
    {
      hangeul: "미안해요",
      pelafalan: "mianhaeyo",
      arti: "Maaf",
      contohKalimat: "미안해요, 실수였어요.",
      pelafalanKalimat: "Mianhaeyo, silsuyeoss-eoyo.",
      artiKalimat: "Maaf, itu adalah kesalahan.",
    },
    {
      hangeul: "고마워요",
      pelafalan: "gomawoyo",
      arti: "Terima kasih",
      contohKalimat: "친절하게 도와줘서 고마워요.",
      pelafalanKalimat: "Chinjeolhage dowajwoseo gomawoyo.",
      artiKalimat: "Terima kasih atas bantuan Anda yang ramah.",
    },
    {
      hangeul: "제발",
      pelafalan: "jebal",
      arti: "Tolong",
      contohKalimat: "제발 도와주세요!",
      pelafalanKalimat: "Jebal dowajuseyo!",
      artiKalimat: "Tolong bantu saya!",
    },
    {
      hangeul: "괜찮아요",
      pelafalan: "gwaenchana",
      arti: "Tidak apa-apa",
      contohKalimat: "괜찮아요, 괜하지 않아요.",
      pelafalanKalimat: "Gwaenchana, gwaenhanji anh-ayo.",
      artiKalimat: "Tidak apa-apa, saya baik-baik saja.",
    },
    {
      hangeul: "믿어요",
      pelafalan: "mideoyo",
      arti: "Percaya",
      contohKalimat: "나는 너를 믿어요.",
      pelafalanKalimat: "Naneun neoleul mideoyo.",
      artiKalimat: "Saya percaya padamu.",
    },
    {
      hangeul: "기다려요",
      pelafalan: "gidaryeoyo",
      arti: "Menunggu",
      contohKalimat: "기다려요, 곧 도착할 거예요.",
      pelafalanKalimat: "Gidaryeoyo, got dochakhaj geoyeyo.",
      artiKalimat: "Tunggu, segera akan tiba.",
    },
    {
      hangeul: "도와주세요",
      pelafalan: "dowajuseyo",
      arti: "Tolong bantu saya",
      contohKalimat: "도와주세요, 어려워요.",
      pelafalanKalimat: "Dowajuseyo, eolyeowoyo.",
      artiKalimat: "Tolong bantu saya, ini sulit.",
    },
    {
      hangeul: "빨리",
      pelafalan: "ppalli",
      arti: "Cepat",
      contohKalimat: "빨리 와요!",
      pelafalanKalimat: "Ppalli wayo!",
      artiKalimat: "Datanglah cepat!",
    },
    {
      hangeul: "천천히",
      pelafalan: "cheoncheonhi",
      arti: "Lambat",
      contohKalimat: "천천히 걸어주세요.",
      pelafalanKalimat: "Cheoncheonhi geol-eojuseyo.",
      artiKalimat: "Tolong berjalan lambat.",
    },
    {
      hangeul: "학교",
      pelafalan: "hakgyo",
      arti: "Sekolah",
      contohKalimat: "오늘 학교에 갈 거예요.",
      pelafalanKalimat: "Oneul hakgyoe gal geoyeyo.",
      artiKalimat: "Hari ini saya akan pergi ke sekolah.",
    },
    {
      hangeul: "책",
      pelafalan: "chaek",
      arti: "Buku",
      contohKalimat: "이 책을 읽었어요.",
      pelafalanKalimat: "I chaeg-eul ilh-eoss-eoyo.",
      artiKalimat: "Saya telah membaca buku ini.",
    },
    {
      hangeul: "친구",
      pelafalan: "chingu",
      arti: "Teman",
      contohKalimat: "나는 좋은 친구가 있어요.",
      pelafalanKalimat: "Naneun joh-eun chinguga iss-eoyo.",
      artiKalimat: "Saya punya teman yang baik.",
    },
  ],

  level2: [
    {
      hangeul: "가방",
      pelafalan: "gabang",
      arti: "Tas",
      contohKalimat: "가방을 어디에 두었나요?",
      pelafalanKalimat: "Gabang-eul eodie du-eonnayo?",
      artiKalimat: "Di mana Anda meletakkan tas?",
    },
    {
      hangeul: "우산",
      pelafalan: "usan",
      arti: "Payung",
      contohKalimat: "비가 오니까 우산이 필요해요.",
      pelafalanKalimat: "Biga onikka usan-i pil-yohaeyo.",
      artiKalimat: "Karena hujan, saya membutuhkan payung.",
    },
    {
      hangeul: "사진",
      pelafalan: "sajin",
      arti: "Foto",
      contohKalimat: "이 사진은 언제 찍었어요?",
      pelafalanKalimat: "I sajin-eun eonje jjig-eoss-eoyo?",
      artiKalimat: "Kapan foto ini diambil?",
    },
    {
      hangeul: "카페",
      pelafalan: "kafe",
      arti: "Kafe",
      contohKalimat: "저는 카페에서 커피를 마셔요.",
      pelafalanKalimat: "Jeoneun kafe-eseo keopi-reul masyeoyo.",
      artiKalimat: "Saya minum kopi di kafe.",
    },
    {
      hangeul: "음식",
      pelafalan: "eumsig",
      arti: "Makanan",
      contohKalimat: "한국 음식을 좋아해요.",
      pelafalanKalimat: "Hanguk eumsig-eul joh-ahae-yo.",
      artiKalimat: "Saya suka makanan Korea.",
    },
    {
      hangeul: "물",
      pelafalan: "mul",
      arti: "Air",
      contohKalimat: "물을 한 잔 주세요.",
      pelafalanKalimat: "Mul-eul han jan juseyo.",
      artiKalimat: "Tolong berikan segelas air.",
    },
    {
      hangeul: "커피",
      pelafalan: "keopi",
      arti: "Kopi",
      contohKalimat: "아침에 커피를 마셔요.",
      pelafalanKalimat: "Achim-e keopi-reul masyeoyo.",
      artiKalimat: "Saya minum kopi di pagi hari.",
    },
    {
      hangeul: "차",
      pelafalan: "cha",
      arti: "Teh",
      contohKalimat: "차 한 잔 주세요.",
      pelafalanKalimat: "Cha han jan juseyo.",
      artiKalimat: "Tolong berikan segelas teh.",
    },
    {
      hangeul: "버스",
      pelafalan: "beoseu",
      arti: "Bus",
      contohKalimat: "어디서 버스를 탈 수 있어요?",
      pelafalanKalimat: "Eodiseo beoseuleul tal su iss-eoyo?",
      artiKalimat: "Di mana saya bisa naik bus?",
    },
    {
      hangeul: "지하철",
      pelafalan: "jihacheol",
      arti: "Kereta bawah tanah",
      contohKalimat: "지하철역에서 내려주세요.",
      pelafalanKalimat: "Jihacheolyeog-eseo naelyeojuseyo.",
      artiKalimat: "Tolong berhenti di stasiun kereta bawah tanah.",
    },
    {
      hangeul: "비행기",
      pelafalan: "bihaenggi",
      arti: "Pesawat",
      contohKalimat: "비행기표를 예약했어요.",
      pelafalanKalimat: "Bihaenggi-pyo-reul yeoyaghaess-eoyo.",
      artiKalimat: "Saya telah memesan tiket pesawat.",
    },
    {
      hangeul: "택시",
      pelafalan: "taegsi",
      arti: "Taksi",
      contohKalimat: "택시를 타고 집에 갈 거예요.",
      pelafalanKalimat: "Taegsileul tago jib-e gal geoyeyo.",
      artiKalimat: "Saya akan pulang dengan taksi.",
    },
    {
      hangeul: "주말",
      pelafalan: "jumal",
      arti: "Akhir pekan",
      contohKalimat: "주말에 무엇을 할 건가요?",
      pelafalanKalimat: "Jumal-e mueos-eul hal geongayo?",
      artiKalimat: "Apa yang akan kamu lakukan akhir pekan ini?",
    },
    {
      hangeul: "공원",
      pelafalan: "gong-won",
      arti: "Taman",
      contohKalimat: "이 공원은 아름답습니다.",
      pelafalanKalimat: "I gong-won-eun aleumdabseubnida.",
      artiKalimat: "Taman ini indah.",
    },
    {
      hangeul: "해변",
      pelafalan: "haebyeon",
      arti: "Pantai",
      contohKalimat: "여름에 해변으로 가고 싶어요.",
      pelafalanKalimat: "Yeoleum-e haebyeon-eulo gago sip-eoyo.",
      artiKalimat: "Saya ingin pergi ke pantai di musim panas.",
    },
    {
      hangeul: "산",
      pelafalan: "san",
      arti: "Gunung",
      contohKalimat: "산에 등산을 가는 것을 좋아해요.",
      pelafalanKalimat: "San-e deungsan-eul ganeun geos-eul joh-ahae-yo.",
      artiKalimat: "Saya suka mendaki gunung.",
    },
    {
      hangeul: "도시",
      pelafalan: "dos-i",
      arti: "Kota",
      contohKalimat: "서울은 대한민국의 수도입니다.",
      pelafalanKalimat: "Seoul-eun Daehanmingug-ui sudoibnida.",
      artiKalimat: "Seoul adalah ibu kota Korea Selatan.",
    },
    {
      hangeul: "쇼핑",
      pelafalan: "syoping",
      arti: "Berbelanja",
      contohKalimat: "주말에 쇼핑을 할 거예요.",
      pelafalanKalimat: "Jumal-e syoping-eul hal geoyeyo.",
      artiKalimat: "Saya akan berbelanja di akhir pekan.",
    },
    {
      hangeul: "영화",
      pelafalan: "yeonghwa",
      arti: "Film",
      contohKalimat: "영화를 보는 것이 좋아요.",
      pelafalanKalimat: "Yeonghwa-reul boneun geos-i joh-ahyo.",
      artiKalimat: "Saya suka menonton film.",
    },
    {
      hangeul: "음악",
      pelafalan: "eum-ak",
      arti: "Musik",
      contohKalimat: "음악을 듣는 것이 편안해요.",
      pelafalanKalimat: "Eum-ag-eul deutneun geos-i pyeon-anhaeyo.",
      artiKalimat: "Saya merasa nyaman mendengarkan musik.",
    },
  ],

  level3: [
    {
      hangeul: "춤",
      pelafalan: "chum",
      arti: "Tari",
      contohKalimat: "춤을 추는 것은 즐거운 일이에요.",
      pelafalanKalimat: "chumeul chuneun geoseun jeulgeoun irieyo.",
      artiKalimat: "Menari itu menyenangkan.",
    },
    {
      hangeul: "운동",
      pelafalan: "undong",
      arti: "Olahraga",
      contohKalimat: "운동을 꾸준히 하는 것은 건강에 좋아요.",
      pelafalanKalimat: "undongeul kkujunhi haneun geoseun geongang-e johayo.",
      artiKalimat: "Berolahraga secara teratur baik untuk kesehatan.",
    },
    {
      hangeul: "여행",
      pelafalan: "yeohaeng",
      arti: "Perjalanan",
      contohKalimat: "여행을 가고 싶어요, 다양한 곳을 방문하고 싶어요.",
      pelafalanKalimat: "yeohaengeul gago sip-eoyo, dayanghan gos-eul bangmunhago sip-eoyo.",
      artiKalimat: "Saya ingin pergi berlibur, ingin mengunjungi tempat-tempat yang beragam.",
    },
    {
      hangeul: "가족",
      pelafalan: "gajok",
      arti: "Keluarga",
      contohKalimat: "가족과 함께 보내는 시간은 소중해요.",
      pelafalanKalimat: "gajogwa hamkke bonaeneun sigan-eun sojunghaeyo.",
      artiKalimat: "Waktu bersama keluarga sangat berharga.",
    },
    {
      hangeul: "부모님",
      pelafalan: "bumonim",
      arti: "Orang tua",
      contohKalimat: "부모님께 감사의 마음을 전해보세요.",
      pelafalanKalimat: "bumonimkke gamsaui ma-eum-eul jeonhaeboseyo.",
      artiKalimat: "Sampaikan rasa terima kasih kepada orang tua Anda.",
    },
    {
      hangeul: "아들",
      pelafalan: "adeul",
      arti: "Putra",
      contohKalimat: "저의 아들은 매우 재미있고 창의적입니다.",
      pelafalanKalimat: "jeoui adeuleun maewu jaemiissgo chang-uicjeogibnida.",
      artiKalimat: "Anak laki-laki saya sangat menyenangkan dan kreatif.",
    },
    {
      hangeul: "딸",
      pelafalan: "ttal",
      arti: "Putri",
      contohKalimat: "딸의 꿈을 응원해주세요, 그녀는 대단한 사람이 될 수 있어요.",
      pelafalanKalimat: "ttalui kkum-eul eung-wonhaejuseyo, geunyeoneun daedanhan salam-i doel su iss-eoyo.",
      artiKalimat: "Dukunglah impian putri Anda, dia bisa menjadi seseorang yang luar biasa.",
    },
    {
      hangeul: "형제",
      pelafalan: "hyeongje",
      arti: "Saudara laki-laki",
      contohKalimat: "저는 두 형제와 한 여동생이 있어요.",
      pelafalanKalimat: "jeoneun du hyeongjewa han yeodongsaeng-i iss-eoyo.",
      artiKalimat: "Saya memiliki dua saudara laki-laki dan satu adik perempuan.",
    },
    {
      hangeul: "자매",
      pelafalan: "jamae",
      arti: "Saudara perempuan",
      contohKalimat: "우리 자매는 서로를 사랑해요.",
      pelafalanKalimat: "uli jamaeneun seololeul salanghaeyo.",
      artiKalimat: "Saudara perempuan kami saling mencintai.",
    },
    {
      hangeul: "할머니",
      pelafalan: "halmeoni",
      arti: "Nenek (dari ibu)",
      contohKalimat: "할머니께서는 항상 따뜻한 미소를 지으시네요.",
      pelafalanKalimat: "halmeonikkes-eoneun hangsang ttatteushan misoleul jieusineyo.",
      artiKalimat: "Nenek selalu menampilkan senyuman hangat.",
    },
    {
      hangeul: "할아버지",
      pelafalan: "hal-abeoji",
      arti: "Kakek (dari ayah)",
      contohKalimat: "저의 할아버지는 어릴 때 이야기를 자주 해주셨어요.",
      pelafalanKalimat: "jeoui hal-abeojineun eolil ttae iyagileul jaju haejusyeosseoyo.",
      artiKalimat: "Kakek saya sering bercerita ketika saya masih kecil.",
    },
    {
      hangeul: "생일",
      pelafalan: "saengil",
      arti: "Ulang tahun",
      contohKalimat: "오늘은 제 생일이에요. 친구들과 함께 파티를 할 거예요.",
      pelafalanKalimat: "oneul-eun je saengilieyo. chingudeulgwa hamkke patileul hal geoyeyo.",
      artiKalimat: "Hari ini adalah ulang tahun saya. Saya akan merayakan pesta dengan teman-teman.",
    },
    {
      hangeul: "선물",
      pelafalan: "seonmul",
      arti: "Hadiah",
      contohKalimat: "생일 선물로 뭐가 좋을지 고민 중이에요.",
      pelafalanKalimat: "saengil seonmullo mwoga joh-eulji gomin jung-ieyo.",
      artiKalimat: "Saya sedang memikirkan apa yang bagus sebagai hadiah ulang tahun.",
    },
    {
      hangeul: "결혼",
      pelafalan: "gyeolhon",
      arti: "Pernikahan",
      contohKalimat: "저는 내년에 결혼할 계획이에요.",
      pelafalanKalimat: "jeoneun naen-yeon-e gyeolhonhal gyeheog-ieyo.",
      artiKalimat: "Saya berencana menikah tahun depan.",
    },
    {
      hangeul: "축하해요",
      pelafalan: "chughahaeyo",
      arti: "Selamat",
      contohKalimat: "결혼을 축하해요! 행복한 미래를 기원해요.",
      pelafalanKalimat: "gyeolhon-eul chughahaeyo! haengboghan milaeleul giwonhaeyo.",
      artiKalimat: "Selamat atas pernikahan! Semoga memiliki masa depan yang bahagia.",
    },
    {
      hangeul: "죄송해요",
      pelafalan: "joesonghaeyo",
      arti: "Maaf",
      contohKalimat: "죄송해요, 실수를 저질렀어요.",
      pelafalanKalimat: "joesonghaeyo, silsuleul jeojilleoss-eoyo.",
      artiKalimat: "Maaf, saya membuat kesalahan.",
    },
    {
      hangeul: "화장실",
      pelafalan: "hwajangsil",
      arti: "Kamar mandi",
      contohKalimat: "화장실은 건물 뒤쪽에 있어요.",
      pelafalanKalimat: "hwajangsil-eun geonmul dwijjog-e iss-eoyo.",
      artiKalimat: "Kamar mandi berada di belakang bangunan.",
    },
    {
      hangeul: "병원",
      pelafalan: "byeong-won",
      arti: "Rumah sakit",
      contohKalimat: "어머니가 병원에 입원했어요.",
      pelafalanKalimat: "eomeoniga byeong-won-e ib-wonhaess-eoyo.",
      artiKalimat: "Ibu saya dirawat di rumah sakit.",
    },
    {
      hangeul: "수영장",
      pelafalan: "suyeongjang",
      arti: "Kolam renang",
      contohKalimat: "여름에는 수영장이 붐비는 편이에요.",
      pelafalanKalimat: "yeoleum-eneun suyeongjang-i bumbineun pyeonieyo.",
      artiKalimat: "Kolam renang ramai pada musim panas.",
    },
    {
      hangeul: "공항",
      pelafalan: "gonghang",
      arti: "Bandara",
      contohKalimat: "출장 때문에 공항에 가야 해요.",
      pelafalanKalimat: "chuljang ttaemun-e gonghang-e ga-ya haeyo.",
      artiKalimat: "Saya harus pergi ke bandara karena tugas bisnis.",
    },
  ],

  level4: [
    {
      hangeul: "놀이공원",
      pelafalan: "nori gongwon",
      arti: "Taman bermain",
      contohKalimat: "오늘은 친구들과 놀이공원에 가요.",
      pelafalanKalimat: "oneul-eun chingudeulgwa nori gongwon-e gayo.",
      artiKalimat: "Hari ini saya pergi ke taman bermain dengan teman-teman.",
    },
    {
      hangeul: "쇼핑몰",
      pelafalan: "syopingmol",
      arti: "Pusat perbelanjaan",
      contohKalimat: "주말에 쇼핑몰에서 옷을 사려고 해요.",
      pelafalanKalimat: "jumal-e syopingmol-eseo os-eul salyeogo haeyo.",
      artiKalimat: "Akhir pekan ini saya berencana untuk membeli pakaian di pusat perbelanjaan.",
    },
    {
      hangeul: "시장",
      pelafalan: "sijang",
      arti: "Pasar",
      contohKalimat: "시장에서 신선한 과일을 구매했어요.",
      pelafalanKalimat: "sijang-eseo sinsunhan gwail-eul gumahaeoss-eoyo.",
      artiKalimat: "Saya membeli buah-buahan segar di pasar.",
    },
    {
      hangeul: "레스토랑",
      pelafalan: "reseutolang",
      arti: "Restoran",
      contohKalimat: "생일 축하를 위해 레스토랑을 예약했어요.",
      pelafalanKalimat: "saeng-il chughaleul wihae reseutolang-eul yeayaghess-eoyo.",
      artiKalimat: "Saya telah memesan restoran untuk merayakan ulang tahun.",
    },
    {
      hangeul: "카페테리아",
      pelafalan: "kapeseteria",
      arti: "Kafetaria",
      contohKalimat: "학교 카페테리아에서 점심을 먹었어요.",
      pelafalanKalimat: "haggyo kapeseteria-eseo jeomsim-eul meog-eoss-eoyo.",
      artiKalimat: "Saya makan siang di kafetaria sekolah.",
    },
    {
      hangeul: "지금",
      pelafalan: "jigeum",
      arti: "Sekarang",
      contohKalimat: "지금 몇 시에요?",
      pelafalanKalimat: "jigeum myeot si-e-yo?",
      artiKalimat: "Sekarang pukul berapa?",
    },
    {
      hangeul: "언제",
      pelafalan: "eonje",
      arti: "Kapan",
      contohKalimat: "언제 여행을 가는 거예요?",
      pelafalanKalimat: "eonje yeohaeng-eul ga-neun geoyeyo?",
      artiKalimat: "Kapan Anda akan pergi berlibur?",
    },
    {
      hangeul: "어디",
      pelafalan: "eodi",
      arti: "Di mana",
      contohKalimat: "친구들은 어디에 있나요?",
      pelafalanKalimat: "chingudeul-eun eodi-e issnayo?",
      artiKalimat: "Di mana teman-teman berada?",
    },
    {
      hangeul: "왜",
      pelafalan: "wae",
      arti: "Mengapa",
      contohKalimat: "왜 이렇게 늦었어요?",
      pelafalanKalimat: "wae ileohge neujeoss-eoyo?",
      artiKalimat: "Mengapa Anda terlambat seperti ini?",
    },
    {
      hangeul: "무엇",
      pelafalan: "mueos",
      arti: "Apa",
      contohKalimat: "무엇을 도와드릴까요?",
      pelafalanKalimat: "mueos-eul dowadeulilkkayo?",
      artiKalimat: "Apa yang bisa saya bantu?",
    },
    {
      hangeul: "어떻게",
      pelafalan: "eotteohge",
      arti: "Bagaimana",
      contohKalimat: "이 일을 어떻게 해야 할까요?",
      pelafalanKalimat: "i il-eul eotteohge haeya halkkayo?",
      artiKalimat: "Bagaimana cara melakukan ini?",
    },
    {
      hangeul: "이해해요",
      pelafalan: "ihaehaeyo",
      arti: "Saya mengerti",
      contohKalimat: "저도 당신의 감정을 이해해요.",
      pelafalanKalimat: "jeodo dangsin-ui gamjeong-eul ihaehaeyo.",
      artiKalimat: "Saya juga memahami perasaan Anda.",
    },
    {
      hangeul: "알겠어요",
      pelafalan: "algesseoyo",
      arti: "Saya mengerti / Oke",
      contohKalimat: "네, 알겠어요. 감사합니다.",
      pelafalanKalimat: "ne, algesseoyo. gamsahamnida.",
      artiKalimat: "Ya, saya mengerti. Terima kasih.",
    },
    {
      hangeul: "몰라요",
      pelafalan: "mollayo",
      arti: "Saya tidak tahu",
      contohKalimat: "그 질문에 대해선 잘 몰라요.",
      pelafalanKalimat: "geu jilmun-e daehaeseon jal mollayo.",
      artiKalimat: "Saya tidak tahu jawabannya untuk pertanyaan itu.",
    },
    {
      hangeul: "대단해요",
      pelafalan: "daedanhaeyo",
      arti: "Hebat / Luar biasa",
      contohKalimat: "당신의 성과에 정말 대단해요!",
      pelafalanKalimat: "dangsin-ui seong-gwa-e jeongmal daedanhaeyo!",
      artiKalimat: "Prestasi Anda benar-benar luar biasa!",
    },
    {
      hangeul: "멋있어요",
      pelafalan: "meos-iss-eoyo",
      arti: "Keren / Kekerenan",
      contohKalimat: "당신은 정말 멋있어요.",
      pelafalanKalimat: "dangsin-eun jeongmal meos-iss-eoyo.",
      artiKalimat: "Anda sangat keren.",
    },
    {
      hangeul: "예쁘다",
      pelafalan: "yeppeuda",
      arti: "Cantik",
      contohKalimat: "그 여자는 정말 예쁘다.",
      pelafalanKalimat: "geu yeojaneun jeongmal yeppeuda.",
      artiKalimat: "Wanita itu sangat cantik.",
    },
    {
      hangeul: "사랑스럽다",
      pelafalan: "salangseuleobda",
      arti: "Manis / Menggemaskan",
      contohKalimat: "아이들은 사랑스러워요.",
      pelafalanKalimat: "aideul-eun salangseuleowoyo.",
      artiKalimat: "Anak-anak sangat menggemaskan.",
    },
    {
      hangeul: "행복하다",
      pelafalan: "haengboghada",
      arti: "Bahagia",
      contohKalimat: "저는 지금 매우 행복해요.",
      pelafalanKalimat: "jeoneun jigeum ma-eu haengbogh-aeyo.",
      artiKalimat: "Saya sangat bahagia sekarang.",
    },
    {
      hangeul: "슬프다",
      pelafalan: "seulpeuda",
      arti: "Sedih",
      contohKalimat: "그 영화는 슬퍼요. 눈물이 나요.",
      pelafalanKalimat: "geu yeonghwaneun seulpeoyo. nunmul-i nayo.",
      artiKalimat: "Film itu menyedihkan. Saya menangis.",
    },
  ],

  level5: [
    {
      hangeul: "화나다",
      pelafalan: "hwanada",
      arti: "Marah",
      contohKalimat: "왜 그렇게 화나요?",
      pelafalanKalimat: "wae geuleohge hwanayo?",
      artiKalimat: "Mengapa Anda begitu marah?",
    },
    {
      hangeul: "무섭다",
      pelafalan: "museobda",
      arti: "Takut",
      contohKalimat: "그 영화는 정말 무섭다.",
      pelafalanKalimat: "geu yeonghwaneun jeongmal museobda.",
      artiKalimat: "Film itu sangat menakutkan.",
    },
    {
      hangeul: "즐겁다",
      pelafalan: "jeulgeobda",
      arti: "Menyenangkan",
      contohKalimat: "함께 있는 시간이 항상 즐겁다.",
      pelafalanKalimat: "hamkke issneun sigan-i hangsang jeulgeobda.",
      artiKalimat: "Waktu bersama selalu menyenangkan.",
    },
    {
      hangeul: "좋다",
      pelafalan: "johda",
      arti: "Baik / Bagus",
      contohKalimat: "이 옷이 정말 좋아요.",
      pelafalanKalimat: "i os-i jeongmal joh-ayo.",
      artiKalimat: "Pakaian ini sangat bagus.",
    },
    {
      hangeul: "나쁘다",
      pelafalan: "nappeuda",
      arti: "Buruk",
      contohKalimat: "그 영화는 별로 나쁘지 않아요.",
      pelafalanKalimat: "geu yeonghwaneun byeollo nappeuji anh-ayo.",
      artiKalimat: "Film itu tidak begitu buruk.",
    },
    {
      hangeul: "맛있다",
      pelafalan: "mas-issda",
      arti: "Enak",
      contohKalimat: "이 음식 정말 맛있다.",
      pelafalanKalimat: "i eumsig jeongmal mas-issda.",
      artiKalimat: "Makanan ini sangat enak.",
    },
    {
      hangeul: "시원하다",
      pelafalan: "siwonhada",
      arti: "Segar",
      contohKalimat: "오늘 날씨가 시원해요.",
      pelafalanKalimat: "oneul nalssiga siwonhaeyo.",
      artiKalimat: "Cuaca hari ini sangat segar.",
    },
    {
      hangeul: "덥다",
      pelafalan: "deopda",
      arti: "Panas",
      contohKalimat: "오늘 날씨가 정말 덥다.",
      pelafalanKalimat: "oneul nalssiga jeongmal deopda.",
      artiKalimat: "Cuaca hari ini sangat panas.",
    },
    {
      hangeul: "추워요",
      pelafalan: "chwuwoyo",
      arti: "Dingin",
      contohKalimat: "겨울에는 밖이 추워요.",
      pelafalanKalimat: "gyeoul-eneun bak-i chwuwoyo.",
      artiKalimat: "Di musim dingin, luar sangat dingin.",
    },
    {
      hangeul: "비오다",
      pelafalan: "bioda",
      arti: "Hujan",
      contohKalimat: "오늘은 비가 올 것 같아요.",
      pelafalanKalimat: "oneul-eun biga ol geos gat-ayo.",
      artiKalimat: "Sepertinya hari ini akan hujan.",
    },
    {
      hangeul: "눈오다",
      pelafalan: "nunoda",
      arti: "Salju",
      contohKalimat: "오늘은 눈이 오네요.",
      pelafalanKalimat: "oneul-eun nuni oneyo.",
      artiKalimat: "Hari ini turun salju.",
    },
    {
      hangeul: "올라가다",
      pelafalan: "ollagada",
      arti: "Naik / Mendaki",
      contohKalimat: "산 꼭대기까지 올라가봤어요.",
      pelafalanKalimat: "san kkogdaegikkaji ollagabwass-eoyo.",
      artiKalimat: "Saya mencoba naik sampai ke puncak gunung.",
    },
    {
      hangeul: "내려가다",
      pelafalan: "naelyeogada",
      arti: "Turun / Menuruni",
      contohKalimat: "산에서 내려가는 길은 험난해요.",
      pelafalanKalimat: "san-eseo naelyeoganeun gil-eun heomnanhaeyo.",
      artiKalimat: "Jalan turun dari gunung sangat sulit.",
    },
    {
      hangeul: "출발",
      pelafalan: "chulbal",
      arti: "Berangkat",
      contohKalimat: "버스가 곧 출발해요.",
      pelafalanKalimat: "beoseuga god chulbalhaeyo.",
      artiKalimat: "Bus akan segera berangkat.",
    },
    {
      hangeul: "도착",
      pelafalan: "dochak",
      arti: "Tiba",
      contohKalimat: "비행기가 서울에 도착했어요.",
      pelafalanKalimat: "bihyanggiga seoul-e dochakhess-eoyo.",
      artiKalimat: "Pesawat tiba di Seoul.",
    },
    {
      hangeul: "반갑다",
      pelafalan: "bangabda",
      arti: "Senang / Suka",
      contohKalimat: "반가워요! 오랜만이에요.",
      pelafalanKalimat: "bangawoyo! olaenman-ieyo.",
      artiKalimat: "Senang bertemu dengan Anda setelah lama.",
    },
    {
      hangeul: "영어",
      pelafalan: "yeongeo",
      arti: "Bahasa Inggris",
      contohKalimat: "영어를 배우고 있어요.",
      pelafalanKalimat: "yeong-eoleul baeugo iss-eoyo.",
      artiKalimat: "Saya sedang belajar bahasa Inggris.",
    },
    {
      hangeul: "수학",
      pelafalan: "su-hag",
      arti: "Matematika",
      contohKalimat: "수학 시험을 잘 봤어요.",
      pelafalanKalimat: "suhag siheom-eul jal bwass-eoyo.",
      artiKalimat: "Saya mendapat nilai bagus dalam ujian matematika.",
    },
    {
      hangeul: "과학",
      pelafalan: "gwahag",
      arti: "Ilmu pengetahuan",
      contohKalimat: "과학 수업이 재미있어요.",
      pelafalanKalimat: "gwahag sueob-i jaemiiss-eoyo.",
      artiKalimat: "Pelajaran ilmu pengetahuan sangat menarik.",
    },
    {
      hangeul: "읽다",
      pelafalan: "ikda",
      arti: "Membaca",
      contohKalimat: "책을 읽는 걸 좋아해요.",
      pelafalanKalimat: "chaeg-eul ilhneun geol joh-ahaeyo.",
      artiKalimat: "Saya suka membaca buku.",
    },
  ],

  level6: [
    {
      hangeul: "쓰다",
      pelafalan: "sseuda",
      arti: "Menulis",
      contohKalimat: "필기를 펜으로 썼어요.",
      pelafalanKalimat: "pilgileul pen-eulo sseoss-eoyo.",
      artiKalimat: "Saya menulis catatan dengan pena.",
    },
    {
      hangeul: "듣다",
      pelafalan: "deudta",
      arti: "Mendengar / Mendengarkan",
      contohKalimat: "노래를 들으면 기분이 좋아져요.",
      pelafalanKalimat: "nolaereul deul-eumyeon gibun-i joh-ajyeoyo.",
      artiKalimat: "Mendengar lagu membuat mood menjadi lebih baik.",
    },
    {
      hangeul: "말하다",
      pelafalan: "malhada",
      arti: "Berbicara / Bicara",
      contohKalimat: "친구와 많이 말하고 싶어요.",
      pelafalanKalimat: "chinguwa manhi malhago sip-eoyo.",
      artiKalimat: "Saya ingin banyak berbicara dengan teman.",
    },
    {
      hangeul: "타다",
      pelafalan: "tada",
      arti: "Naik (Kendaraan)",
      contohKalimat: "버스를 타서 학교에 갔어요.",
      pelafalanKalimat: "beoseuleul taseo hakgyo-e gass-eoyo.",
      artiKalimat: "Saya naik bus ke sekolah.",
    },
    {
      hangeul: "오다",
      pelafalan: "oda",
      arti: "Datang / Datang (Terdekat)",
      contohKalimat: "친구가 내일 방문할 거예요.",
      pelafalanKalimat: "chinguga naeil bangmunhal geoyeyo.",
      artiKalimat: "Teman akan datang besok.",
    },
    {
      hangeul: "가다",
      pelafalan: "gada",
      arti: "Pergi / Pergi (Terdekat)",
      contohKalimat: "내일 도서관에 가려고 해요.",
      pelafalanKalimat: "naeil doseogwan-e galyeogo haeyo.",
      artiKalimat: "Saya akan pergi ke perpustakaan besok.",
    },
    {
      hangeul: "먹다",
      pelafalan: "meokda",
      arti: "Makan",
      contohKalimat: "점심에 뭘 먹을까요?",
      pelafalanKalimat: "jeomsim-e mwol meog-eulkka-yo?",
      artiKalimat: "Apa yang akan saya makan untuk makan siang?",
    },
    {
      hangeul: "마시다",
      pelafalan: "masida",
      arti: "Minum",
      contohKalimat: "물을 자주 마셔야 해요.",
      pelafalanKalimat: "mul-eul jaju masyeoya haeyo.",
      artiKalimat: "Anda harus minum air secara teratur.",
    },
    {
      hangeul: "자다",
      pelafalan: "jada",
      arti: "Tidur",
      contohKalimat: "밤에 일찍 자는 게 좋아요.",
      pelafalanKalimat: "bam-e iljjig janeun ge joh-ayo.",
      artiKalimat: "Tidur lebih awal di malam hari bagus.",
    },
    {
      hangeul: "일어나다",
      pelafalan: "ileonada",
      arti: "Bangun / Bangun (Dari Tidur)",
      contohKalimat: "아침에 일찍 일어나요.",
      pelafalanKalimat: "achim-e iljjig ileonayo.",
      artiKalimat: "Saya bangun pagi-pagi.",
    },
    {
      hangeul: "일하다",
      pelafalan: "ilhada",
      arti: "Bekerja",
      contohKalimat: "오늘은 일하느라 바쁘다.",
      pelafalanKalimat: "oneul-eun ilhaneula bappeuda.",
      artiKalimat: "Hari ini sibuk karena bekerja.",
    },
    {
      hangeul: "공부하다",
      pelafalan: "gongbuhada",
      arti: "Belajar",
      contohKalimat: "매일 저녁에 공부해요.",
      pelafalanKalimat: "maeil jeonyeog-e gongbuh-aeyo.",
      artiKalimat: "Saya belajar setiap malam.",
    },
    {
      hangeul: "연습하다",
      pelafalan: "yeonseubhada",
      arti: "Berlatih",
      contohKalimat: "축구를 연습하면서 능력이 늘어났어요.",
      pelafalanKalimat: "chugguleul yeonseubhamyeonseo neunglyeog-i neul-eonass-eoyo.",
      artiKalimat: "Kemampuan saya meningkat saat berlatih sepak bola.",
    },
    {
      hangeul: "노래하다",
      pelafalan: "nolaehada",
      arti: "Bernyanyi",
      contohKalimat: "친구들과 함께 노래해요.",
      pelafalanKalimat: "chingudeulgwa hamkke nolaehaeyo.",
      artiKalimat: "Saya bernyanyi bersama teman-teman.",
    },
    {
      hangeul: "춤추다",
      pelafalan: "chumchuda",
      arti: "Menari",
      contohKalimat: "파티에서 춤추는 것을 좋아해요.",
      pelafalanKalimat: "patieseo chumchuneun geos-eul joh-ahaeyo.",
      artiKalimat: "Saya suka menari di pesta.",
    },
    {
      hangeul: "여행하다",
      pelafalan: "yeohaenghada",
      arti: "Berpergian",
      contohKalimat: "여름에 해외로 여행할 거예요.",
      pelafalanKalimat: "yeoleum-e haeoelo yeohaenghal geoyeyo.",
      artiKalimat: "Saya akan berpergian ke luar negeri pada musim panas.",
    },
    {
      hangeul: "쇼핑하다",
      pelafalan: "syopinghada",
      arti: "Berbelanja",
      contohKalimat: "주말에 쇼핑하러 갈 거예요.",
      pelafalanKalimat: "jumal-e syopinghaleo gal geoyeyo.",
      artiKalimat: "Saya akan pergi berbelanja pada akhir pekan.",
    },
    {
      hangeul: "사진찍다",
      pelafalan: "sajinjjigda",
      arti: "Mengambil foto",
      contohKalimat: "산에서 아름다운 사진을 찍었어요.",
      pelafalanKalimat: "san-eseo aleumdaun sajin-eul jjig-eoss-eoyo.",
      artiKalimat: "Saya mengambil foto indah di gunung.",
    },
    {
      hangeul: "휴가",
      pelafalan: "hyuga",
      arti: "Liburan",
      contohKalimat: "여름에 휴가를 계획하고 있어요.",
      pelafalanKalimat: "yeoleum-e hyugaleul gyehoeghago iss-eoyo.",
      artiKalimat: "Saya merencanakan liburan pada musim panas.",
    },
    {
      hangeul: "꽃",
      pelafalan: "kkot",
      arti: "Bunga",
      contohKalimat: "봄에 꽃들이 아름답다.",
      pelafalanKalimat: "bom-e kkotdeul-i aleumdabda.",
      artiKalimat: "Bunga-bunga indah di musim semi.",
    },
  ],

  level7: [
    {
      hangeul: "나무",
      pelafalan: "namu",
      arti: "Pohon",
      contohKalimat: "저기 저 나무 아래에 앉아 봐요.",
      pelafalanKalimat: "jeogi jeo namu alae-e anj-a bwayo.",
      artiKalimat: "Coba duduk di bawah pohon itu.",
    },
    {
      hangeul: "구름",
      pelafalan: "gureum",
      arti: "Awan",
      contohKalimat: "하늘에 흩날리는 구름이 예뻐요.",
      pelafalanKalimat: "haneul-e heutnallineun gureum-i yeppeoyo.",
      artiKalimat: "Awan bergerak di langit terlihat indah.",
    },
    {
      hangeul: "별",
      pelafalan: "byeol",
      arti: "Bintang",
      contohKalimat: "밤하늘에 반짝이는 별들이 아름답다.",
      pelafalanKalimat: "bamhaneul-e banjjag-ineun byeoldeul-i aleumdabda.",
      artiKalimat: "Bintang-bintang berkelap-kelip di langit malam terlihat indah.",
    },
    {
      hangeul: "달",
      pelafalan: "dal",
      arti: "Bulan",
      contohKalimat: "저녁에 하늘에 달이 떴어요.",
      pelafalanKalimat: "jeonyeog-e haneul-e dal-i tteoss-eoyo.",
      artiKalimat: "Bulan muncul di langit pada sore hari.",
    },
    {
      hangeul: "태양",
      pelafalan: "taeyang",
      arti: "Matahari",
      contohKalimat: "아침에 태양이 떠오르면 기분이 좋아져요.",
      pelafalanKalimat: "achim-e taeyang-i tteooleumyeon gibun-i joh-ajyeoyo.",
      artiKalimat: "Saya merasa senang ketika matahari terbit di pagi hari.",
    },
    {
      hangeul: "바다",
      pelafalan: "bada",
      arti: "Laut",
      contohKalimat: "여름에 바다로 여행하고 싶어요.",
      pelafalanKalimat: "yeoleum-e bada-lo yeohaenghago sip-eoyo.",
      artiKalimat: "Saya ingin berlibur ke pantai pada musim panas.",
    },
    {
      hangeul: "강",
      pelafalan: "gang",
      arti: "Sungai",
      contohKalimat: "산 꼭대기에서 강을 내려다봐요.",
      pelafalanKalimat: "san kkogdaegieseo gang-eul naelyeodabwayo.",
      artiKalimat: "Dari puncak gunung, melihat ke bawah sungai.",
    },
    {
      hangeul: "산",
      pelafalan: "san",
      arti: "Gunung",
      contohKalimat: "가을에 산에 등산을 가요.",
      pelafalanKalimat: "ga-eul-e san-e deungsan-eul gayo.",
      artiKalimat: "Pada musim gugur, saya pergi mendaki gunung.",
    },
    {
      hangeul: "섬",
      pelafalan: "seom",
      arti: "Pulau",
      contohKalimat: "여름 휴가 때 섬에 갈 거예요.",
      pelafalanKalimat: "yeoleum hyuga ttae seom-e gal geoyeyo.",
      artiKalimat: "Saya akan pergi ke pulau saat liburan musim panas.",
    },
    {
      hangeul: "저녁",
      pelafalan: "jeonyeok",
      arti: "Malam (Makan Malam)",
      contohKalimat: "저녁 식사는 무엇을 먹을까요?",
      pelafalanKalimat: "jeonyeok sigsaneun mueos-eul meog-eulkka-yo?",
      artiKalimat: "Apa yang akan kita makan untuk makan malam?",
    },
    {
      hangeul: "아침",
      pelafalan: "achim",
      arti: "Pagi",
      contohKalimat: "아침에 일찍 일어나는 것이 좋아요.",
      pelafalanKalimat: "achim-e iljjig ileonaneun geos-i joh-ayo.",
      artiKalimat: "Bangun pagi lebih awal itu baik.",
    },
    {
      hangeul: "점심",
      pelafalan: "jeomsim",
      arti: "Makan siang",
      contohKalimat: "오늘 점심은 무엇을 먹을까요?",
      pelafalanKalimat: "oneul jeomsim-eun mueos-eul meog-eulkka-yo?",
      artiKalimat: "Apa yang akan kita makan untuk makan siang hari ini?",
    },
    {
      hangeul: "배고파요",
      pelafalan: "baegopayo",
      arti: "Lapar",
      contohKalimat: "점심 먹으러 갈까요? 나도 배고파요.",
      pelafalanKalimat: "jeomsim meog-euleo galkkayo? nado baegopayo.",
      artiKalimat: "Ayo pergi makan siang? Saya juga lapar.",
    },
    {
      hangeul: "목말라요",
      pelafalan: "mogmallayo",
      arti: "Haus",
      contohKalimat: "물 마시러 가요. 목말라요.",
      pelafalanKalimat: "mul masileo gayo. mogmallayo.",
      artiKalimat: "Ayo minum air. Saya haus.",
    },
    {
      hangeul: "춥다",
      pelafalan: "chupda",
      arti: "Dingin",
      contohKalimat: "밖이 춥네요. 따뜻하게 입으세요.",
      pelafalanKalimat: "bakk-i chupneyo. ttatteushage ib-euseyo.",
      artiKalimat: "Luar dingin. Kenakan pakaian hangat.",
    },
    {
      hangeul: "덥다",
      pelafalan: "deopda",
      arti: "Panas",
      contohKalimat: "오늘 날씨가 덥네요. 물 마시는 게 좋아요.",
      pelafalanKalimat: "oneul nalssiga deobneyo. mul masineun ge joh-ayo.",
      artiKalimat: "Cuaca hari ini panas. Minum air itu baik.",
    },
    {
      hangeul: "감기",
      pelafalan: "gamgi",
      arti: "Flu / Pilek",
      contohKalimat: "감기에 걸렸어요. 푹 쉬세요.",
      pelafalanKalimat: "gamgie geollyeoss-eoyo. pug swiseyo.",
      artiKalimat: "Saya kena flu. Istirahatlah dengan baik.",
    },
    {
      hangeul: "아픈",
      pelafalan: "apeun",
      arti: "Sakit",
      contohKalimat: "동생이 아픈 것 같아요. 의사에게 가봐야겠어요.",
      pelafalanKalimat: "dongsaeng-i apeun geos gat-ayo. uisaege gabwayagesseoyo.",
      artiKalimat: "Sepertinya adik saya sakit. Saya harus pergi ke dokter.",
    },
    {
      hangeul: "즐거운",
      pelafalan: "jeulgeoun",
      arti: "Menyenangkan",
      contohKalimat: "즐거운 시간을 보냈어요. 친구들과 함께 웃었어요.",
      pelafalanKalimat: "jeulgeoun sigan-eul bonaess-eoyo. chingudeulgwa hamkke us-eoss-eoyo.",
      artiKalimat: "Saya memiliki waktu yang menyenangkan. Saya tertawa bersama teman-teman.",
    },
    {
      hangeul: "시간",
      pelafalan: "sigan",
      arti: "Waktu",
      contohKalimat: "시간이 얼마나 남았어요?",
      pelafalanKalimat: "sigan-i eolmana nam-ass-eoyo?",
      artiKalimat: "Berapa lama waktu yang tersisa?",
    },
  ],

  level8: [
    {
      hangeul: "데이트",
      pelafalan: "deiteu",
      arti: "Kencan",
      contohKalimat: "오늘 밤에 데이트가 있어요.",
      pelafalanKalimat: "Oneul bame deiteuga isseoyo.",
      artiKalimat: "Ada kencan malam ini.",
    },
    {
      hangeul: "친구",
      pelafalan: "chingu",
      arti: "Teman",
      contohKalimat: "저의 친구는 항상 저를 지지해줍니다.",
      pelafalanKalimat: "Jeoui chinguneun hangsang jeoreul jijihaejumida.",
      artiKalimat: "Teman saya selalu mendukung saya.",
    },
    {
      hangeul: "영화관",
      pelafalan: "yeonghwagwan",
      arti: "Bioskop",
      contohKalimat: "오늘 저녁에 영화관에 갈 거예요.",
      pelafalanKalimat: "Oneul jeonyeoke yeonghwagwane gal geoyeyo.",
      artiKalimat: "Saya akan pergi ke bioskop malam ini.",
    },
    {
      hangeul: "공연",
      pelafalan: "gongyeon",
      arti: "Pertunjukan",
      contohKalimat: "이번 주말에 좋은 공연을 볼 수 있을 거예요.",
      pelafalanKalimat: "Ibeon jumare joheun gongyeon-eul bol su iss-eul geoyeyo.",
      artiKalimat: "Akhir pekan ini saya bisa menonton pertunjukan bagus.",
    },
    {
      hangeul: "콘서트",
      pelafalan: "konseoteu",
      arti: "Konser",
      contohKalimat: "내일 친구와 함께 콘서트에 갈 거예요.",
      pelafalanKalimat: "Naeil chinguwa hamkke konseoteue gal geoyeyo.",
      artiKalimat: "Besok saya akan pergi ke konser bersama teman.",
    },
    {
      hangeul: "마트",
      pelafalan: "mateu",
      arti: "Supermarket",
      contohKalimat: "야채를 사러 마트에 갔어요.",
      pelafalanKalimat: "Yachaeleul sal-eo mateue gass-eoyo.",
      artiKalimat: "Saya pergi ke supermarket untuk membeli sayuran.",
    },
    {
      hangeul: "서점",
      pelafalan: "seojom",
      arti: "Toko buku",
      contohKalimat: "저는 주말마다 서점에 가서 책을 읽어요.",
      pelafalanKalimat: "Jeoneun jumal-mada seojom-e gaseo chaeg-eul ilgeo-yo.",
      artiKalimat: "Setiap akhir pekan, saya pergi ke toko buku dan membaca buku.",
    },
    {
      hangeul: "박물관",
      pelafalan: "bangmulgwan",
      arti: "Museum",
      contohKalimat: "내일 친구와 함께 박물관에 갈 예정이에요.",
      pelafalanKalimat: "Naeil chinguwa hamkke bangmulgwan-e gal yejeong-ieyo.",
      artiKalimat: "Besok saya berencana pergi ke museum bersama teman.",
    },
    {
      hangeul: "주말",
      pelafalan: "jumal",
      arti: "Akhir pekan",
      contohKalimat: "주말에는 친구들과 함께 시간을 보내는 게 좋아요.",
      pelafalanKalimat: "Jumal-eneun chingudeulgwa hamkke sigan-eul bonaeneun ge joh-ayo.",
      artiKalimat: "Saya suka menghabiskan waktu dengan teman-teman pada akhir pekan.",
    },
    {
      hangeul: "휴식",
      pelafalan: "hyusig",
      arti: "Istirahat",
      contohKalimat: "이번 주말에는 휴식을 취할 계획이에요.",
      pelafalanKalimat: "Ibeon jumal-eneun hyusig-eul chwihal gyehoeg-ieyo.",
      artiKalimat: "Pada akhir pekan ini, saya berencana untuk istirahat.",
    },
    {
      hangeul: "손님",
      pelafalan: "sonnim",
      arti: "Tamu",
      contohKalimat: "오늘 저녁에 손님이 오셨어요.",
      pelafalanKalimat: "Oneul jeonyeoke sonnim-i osyeoss-eoyo.",
      artiKalimat: "Tamu datang malam ini.",
    },
    {
      hangeul: "선물",
      pelafalan: "seonmul",
      arti: "Hadiah",
      contohKalimat: "생일 선물을 준비했어요.",
      pelafalanKalimat: "Saeng-il seonmul-eul junbihaess-eoyo.",
      artiKalimat: "Saya menyiapkan hadiah ulang tahun.",
    },
    {
      hangeul: "식사",
      pelafalan: "siksa",
      arti: "Makan",
      contohKalimat: "오늘 저녁은 어디서 식사할까요?",
      pelafalanKalimat: "Oneul jeonyeog-eun eodiseo siksa-halkkayo?",
      artiKalimat: "Dimana kita akan makan malam ini?",
    },
    {
      hangeul: "초대",
      pelafalan: "chodae",
      arti: "Undangan",
      contohKalimat: "친구에게 생일 파티 초대장을 받았어요.",
      pelafalanKalimat: "Chinguege saeng-il pati chodaejang-eul bad-ass-eoyo.",
      artiKalimat: "Saya menerima undangan pesta ulang tahun dari teman.",
    },
    {
      hangeul: "친절",
      pelafalan: "chinjeol",
      arti: "Ramah",
      contohKalimat: "그 분은 항상 친절해요.",
      pelafalanKalimat: "Geu bun-eun hangsang chinjeolhaeyo.",
      artiKalimat: "Orang itu selalu ramah.",
    },
    {
      hangeul: "명절",
      pelafalan: "myeongjeol",
      arti: "Hari raya",
      contohKalimat: "명절 때 가족들과 함께 모여요.",
      pelafalanKalimat: "Myeongjeol ttae gajogdeulgwa hamkke moyeoyo.",
      artiKalimat: "Pada hari raya, kami berkumpul bersama keluarga.",
    },
    {
      hangeul: "연휴",
      pelafalan: "yeonhyu",
      arti: "Liburan",
      contohKalimat: "연휴에는 여행을 가는 게 좋아요.",
      pelafalanKalimat: "Yeonhyue-neun yeohaeng-eul ganeun ge joh-ayo.",
      artiKalimat: "Pergi berlibur selama liburan adalah hal yang bagus.",
    },
    {
      hangeul: "국제",
      pelafalan: "gugje",
      arti: "Internasional",
      contohKalimat: "국제 회의가 다음 주에 열릴 예정입니다.",
      pelafalanKalimat: "Gugje hoe-iga da-eum jue yeollil yejeong-imnida.",
      artiKalimat: "Konferensi internasional akan diadakan minggu depan.",
    },
    {
      hangeul: "교통",
      pelafalan: "gyotong",
      arti: "Transportasi",
      contohKalimat: "이 도시의 교통은 편리해요.",
      pelafalanKalimat: "I dosiui gyotong-eun pyeonlihaeyo.",
      artiKalimat: "Transportasi di kota ini sangat nyaman.",
    },
    {
      hangeul: "사업",
      pelafalan: "sa-eob",
      arti: "Bisnis",
      contohKalimat: "그는 작은 사업을 시작했어요.",
      pelafalanKalimat: "Geuneun jageun sa-eob-eul sijaghaess-eoyo.",
      artiKalimat: "Dia memulai bisnis kecil.",
    },
  ],

  level9: [
    {
      hangeul: "경제",
      pelafalan: "gyeongje",
      arti: "Ekonomi",
      contohKalimat: "경제 상황이 어려워요.",
      pelafalanKalimat: "Gyeongje sanghwang-i eoryeowoyo.",
      artiKalimat: "Kondisi ekonomi sulit.",
    },
    {
      hangeul: "교육",
      pelafalan: "gyoyuk",
      arti: "Pendidikan",
      contohKalimat: "교육은 인생의 중요한 부분입니다.",
      pelafalanKalimat: "Gyoyug-eun insaeng-ui jung-yohan bubunimnida.",
      artiKalimat: "Pendidikan adalah bagian penting dalam hidup.",
    },
    {
      hangeul: "문화",
      pelafalan: "munhwa",
      arti: "Budaya",
      contohKalimat: "우리 나라는 풍부한 문화를 가지고 있어요.",
      pelafalanKalimat: "Uli nala-neun pungbuhan munhwa-reul gajigo iss-eoyo.",
      artiKalimat: "Negara kita memiliki budaya yang kaya.",
    },
    {
      hangeul: "음식",
      pelafalan: "eumsik",
      arti: "Makanan",
      contohKalimat: "한국 음식은 매우 맛있어요.",
      pelafalanKalimat: "Hanguk eumsig-eun maeu masiss-eoyo.",
      artiKalimat: "Makanan Korea sangat lezat.",
    },
    {
      hangeul: "요리",
      pelafalan: "yoli",
      arti: "Masak",
      contohKalimat: "요리를 배우는 것이 즐겁습니다.",
      pelafalanKalimat: "Yoli-leul baeuneun geos-i jeulgeobseubnida.",
      artiKalimat: "Belajar memasak itu menyenangkan.",
    },
    {
      hangeul: "미술",
      pelafalan: "misul",
      arti: "Seni rupa",
      contohKalimat: "미술 갤러리에 갔어요.",
      pelafalanKalimat: "Misul gaellie-e gass-eoyo.",
      artiKalimat: "Saya pergi ke galeri seni rupa.",
    },
    {
      hangeul: "음악",
      pelafalan: "eumak",
      arti: "Musik",
      contohKalimat: "음악을 듣는 것이 좋아요.",
      pelafalanKalimat: "Eumag-eul deudneun geos-i joh-ayo.",
      artiKalimat: "Saya suka mendengarkan musik.",
    },
    {
      hangeul: "체육",
      pelafalan: "cheyuk",
      arti: "Olahraga",
      contohKalimat: "학교에서 체육 시간이 제일 좋아요.",
      pelafalanKalimat: "Haggyo-eseo cheyug sigan-i jeil joh-ayo.",
      artiKalimat: "Waktu olahraga di sekolah adalah yang paling saya sukai.",
    },
    {
      hangeul: "수영",
      pelafalan: "suyeong",
      arti: "Renang",
      contohKalimat: "여름에 수영을 즐겨요.",
      pelafalanKalimat: "Yeoleum-e suyeong-eul jeulgyeoyo.",
      artiKalimat: "Saya menikmati berenang di musim panas.",
    },
    {
      hangeul: "등산",
      pelafalan: "deungsan",
      arti: "Pendakian gunung",
      contohKalimat: "저는 자연을 즐기기 위해 등산을 합니다.",
      pelafalanKalimat: "Jeoneun jayeon-eul jeulgigi wihae deungsan-eul hamnida.",
      artiKalimat: "Saya melakukan pendakian gunung untuk menikmati alam.",
    },
    {
      hangeul: "자전거",
      pelafalan: "jajeongeo",
      arti: "Sepeda",
      contohKalimat: "주말에 친구들과 자전거 타기를 즐겨요.",
      pelafalanKalimat: "Jumal-e chingudeulgwa jajeongeo tagileul jeulgyeoyo.",
      artiKalimat: "Saya menikmati bersepeda bersama teman-teman di akhir pekan.",
    },
    {
      hangeul: "쇼핑",
      pelafalan: "syoping",
      arti: "Belanja",
      contohKalimat: "주말에 쇼핑을 하고 싶어요.",
      pelafalanKalimat: "Jumal-e syoping-eul hago sip-eoyo.",
      artiKalimat: "Saya ingin berbelanja di akhir pekan.",
    },
    {
      hangeul: "영화",
      pelafalan: "yeonghwa",
      arti: "Film",
      contohKalimat: "영화를 보는 것이 좋아요.",
      pelafalanKalimat: "Yeonghwa-leul boneun geos-i joh-ayo.",
      artiKalimat: "Saya suka menonton film.",
    },
    {
      hangeul: "읽기",
      pelafalan: "ilkki",
      arti: "Membaca",
      contohKalimat: "책 읽기를 취미로 가지고 있어요.",
      pelafalanKalimat: "Chaeg ilggi-leul chwimi-lo gajigo iss-eoyo.",
      artiKalimat: "Saya memiliki membaca buku sebagai hobi.",
    },
    {
      hangeul: "쓰기",
      pelafalan: "sseugi",
      arti: "Menulis",
      contohKalimat: "일기 쓰기가 일상의 일이에요.",
      pelafalanKalimat: "Ilgi sseugi-ga ilsang-ui il-ieyo.",
      artiKalimat: "Menulis jurnal adalah bagian dari rutinitas sehari-hari.",
    },
    {
      hangeul: "듣기",
      pelafalan: "deudgi",
      arti: "Mendengarkan",
      contohKalimat: "음악 듣기를 통해 스트레스를 푸는 걸 좋아해요.",
      pelafalanKalimat: "Eum-ag deudgi-leul tonghae seuteulesseuleseuleul puneun geol joh-ahaeyo.",
      artiKalimat: "Saya menyukai meredakan stres dengan mendengarkan musik.",
    },
    {
      hangeul: "말하기",
      pelafalan: "malhagi",
      arti: "Berbicara",
      contohKalimat: "새로운 언어 배우고 말하기 연습을 합니다.",
      pelafalanKalimat: "Saeroun eon-eo baeugo malhagi yeonseub-eul hamnida.",
      artiKalimat: "Saya berlatih berbicara setelah belajar bahasa baru.",
    },
    {
      hangeul: "사진",
      pelafalan: "sajin",
      arti: "Foto",
      contohKalimat: "여행 사진을 찍는 걸 좋아해요.",
      pelafalanKalimat: "Yeohaeng sajin-eul jjigneun geol joh-ahaeyo.",
      artiKalimat: "Saya suka mengambil foto saat berwisata.",
    },
    {
      hangeul: "여행",
      pelafalan: "yeohaeng",
      arti: "Wisata",
      contohKalimat: "여행을 계획 중이에요.",
      pelafalanKalimat: "Yeohaeng-eul gyehoeg jung-ieyo.",
      artiKalimat: "Saya sedang merencanakan perjalanan.",
    },
    {
      hangeul: "캠핑",
      pelafalan: "kaemping",
      arti: "Kemah",
      contohKalimat: "가족과 함께 캠핑을 갈 거예요.",
      pelafalanKalimat: "Gajoggwa hamkke kaemping-eul gal geoyeyo.",
      artiKalimat: "Saya akan pergi berkemah bersama keluarga.",
    },
  ],

  level10: [
    {
      hangeul: "등록",
      pelafalan: "deungnok",
      arti: "Pendaftaran",
      contohKalimat: "이메일 주소를 등록하세요.",
      pelafalanKalimat: "imeil jusoreul deungnokhaseyo.",
      artiKalimat: "Silakan daftarkan alamat email Anda.",
    },
    {
      hangeul: "출발",
      pelafalan: "chulbal",
      arti: "Berangkat",
      contohKalimat: "버스가 곧 출발합니다.",
      pelafalanKalimat: "beoseuga got chulbalhamnida.",
      artiKalimat: "Bus akan segera berangkat.",
    },
    {
      hangeul: "도착",
      pelafalan: "dochak",
      arti: "Tiba",
      contohKalimat: "비행기가 3시에 도착합니다.",
      pelafalanKalimat: "bihaenggiga samsi-e dochakhapnida.",
      artiKalimat: "Pesawat tiba pada pukul 3.",
    },
    {
      hangeul: "경험",
      pelafalan: "gyeongheom",
      arti: "Pengalaman",
      contohKalimat: "다양한 문화를 경험해보세요.",
      pelafalanKalimat: "dayanghan munhwareul gyeongheomhaeboseyo.",
      artiKalimat: "Cobalah untuk mengalami berbagai budaya.",
    },
    {
      hangeul: "추억",
      pelafalan: "chu-eok",
      arti: "Kenangan",
      contohKalimat: "저희는 좋은 추억을 만들었어요.",
      pelafalanKalimat: "jeohuineun joeun chu-eogeul mandeuleosseoyo.",
      artiKalimat: "Kami telah menciptakan kenangan yang indah.",
    },
    {
      hangeul: "계획",
      pelafalan: "gyehoeg",
      arti: "Rencana",
      contohKalimat: "여행 계획을 세우세요.",
      pelafalanKalimat: "yeohaeng gyehoeg-eul seuseuseyo.",
      artiKalimat: "Buatlah rencana perjalanan Anda.",
    },
    {
      hangeul: "목표",
      pelafalan: "mokpyo",
      arti: "Tujuan",
      contohKalimat: "성공을 위한 목표를 설정하세요.",
      pelafalanKalimat: "seong-gong-eul wihan mokpyo-eul seolsaehaseyo.",
      artiKalimat: "Tetapkan tujuan untuk kesuksesan.",
    },
    {
      hangeul: "성공",
      pelafalan: "seong-gong",
      arti: "Sukses",
      contohKalimat: "열심히 노력하면 성공할 수 있어요.",
      pelafalanKalimat: "yeolsimhi nolyeoghamyeon seong-gonghal su iss-eoyo.",
      artiKalimat: "Jika Anda bekerja keras, Anda bisa sukses.",
    },
    {
      hangeul: "실패",
      pelafalan: "silpae",
      arti: "Gagal",
      contohKalimat: "실패는 성공의 어머니라고 해요.",
      pelafalanKalimat: "silpaeneun seong-gong-ui eomeonilago haeyo.",
      artiKalimat: "Mereka bilang kegagalan adalah ibu dari kesuksesan.",
    },
    {
      hangeul: "행복",
      pelafalan: "haengbog",
      arti: "Bahagia",
      contohKalimat: "가족과 함께 있는 것이 행복해요.",
      pelafalanKalimat: "gajog-gwa hamkke issneun geos-i haengboghaeyo.",
      artiKalimat: "Bahagia berada bersama keluarga.",
    },
    {
      hangeul: "슬픔",
      pelafalan: "seulpeum",
      arti: "Kesedihan",
      contohKalimat: "그녀는 슬픔에 잠겼어요.",
      pelafalanKalimat: "geunyeoneun seulpeum-e jamgyeosseoyo.",
      artiKalimat: "Dia terjebak dalam kesedihan.",
    },
    {
      hangeul: "사랑",
      pelafalan: "sarang",
      arti: "Cinta",
      contohKalimat: "나는 그녀를 사랑해요.",
      pelafalanKalimat: "naneun geunyeoleul saranghaeyo.",
      artiKalimat: "Aku mencintainya.",
    },
    {
      hangeul: "우정",
      pelafalan: "ujeong",
      arti: "Persahabatan",
      contohKalimat: "우리는 오랜 우정으로 연결되어 있어요.",
      pelafalanKalimat: "ulineun olaen ujeong-eulo yeon-gyeol doe-eo iss-eoyo.",
      artiKalimat: "Kita terhubung dengan persahabatan yang lama.",
    },
    {
      hangeul: "가족",
      pelafalan: "gajok",
      arti: "Keluarga",
      contohKalimat: "가족 모두가 모여 행복한 시간을 보냈어요.",
      pelafalanKalimat: "gajog moduga moyeo haengboghan sigan-eul bonaess-eoyo.",
      artiKalimat: "Seluruh keluarga berkumpul dan menghabiskan waktu bahagia.",
    },
    {
      hangeul: "친구",
      pelafalan: "chingu",
      arti: "Teman",
      contohKalimat: "나의 친구는 항상 나를 지지해줘요.",
      pelafalanKalimat: "naui chinguneun hangsang naleul jijihaejwoyo.",
      artiKalimat: "Teman-temanku selalu mendukungku.",
    },
    {
      hangeul: "사회",
      pelafalan: "sahoe",
      arti: "Masyarakat",
      contohKalimat: "우리는 더 나은 사회를 만들기 위해 노력해야 해요.",
      pelafalanKalimat: "ulineun deo na-eun sahoereul mandeulgi wihae nolyeoghaeya haeyo.",
      artiKalimat: "Kita harus berusaha untuk menciptakan masyarakat yang lebih baik.",
    },
    {
      hangeul: "경제",
      pelafalan: "gyeongje",
      arti: "Ekonomi",
      contohKalimat: "국가의 경제 성장이 중요합니다.",
      pelafalanKalimat: "guggaui gyeongje seongjang-i jung-yohabnida.",
      artiKalimat: "Pertumbuhan ekonomi negara sangat penting.",
    },
    {
      hangeul: "정치",
      pelafalan: "jeongchi",
      arti: "Politik",
      contohKalimat: "정치에 관심을 가지는 것은 시민의 권리입니다.",
      pelafalanKalimat: "jeongchie gwansim-eul gajineun geos-eun simin-ui gwonliibnida.",
      artiKalimat: "Mempunyai minat dalam politik adalah hak warga negara.",
    },
    {
      hangeul: "환경",
      pelafalan: "hwangyeong",
      arti: "Lingkungan",
      contohKalimat: "우리는 지구 환경을 보호해야 합니다.",
      pelafalanKalimat: "ulineun jigu hwangyeong-eul bohohaeoya habnida.",
      artiKalimat: "Kita harus melindungi lingkungan bumi.",
    },
    {
      hangeul: "건강",
      pelafalan: "geongang",
      arti: "Kesehatan",
      contohKalimat: "건강을 가장 큰 자산으로 여기세요.",
      pelafalanKalimat: "geongang-eul gajang keun jasan-eulo yeogiseyo.",
      artiKalimat: "Anggaplah kesehatan sebagai aset terbesarmu.",
    },
  ],

  level11: [
    {
      hangeul: "미래",
      pelafalan: "mirae",
      arti: "Masa depan",
      contohKalimat: "우리는 미래를 준비해야 합니다.",
      pelafalanKalimat: "ulineun miraereul junbihaeya habnida.",
      artiKalimat: "Kita harus mempersiapkan masa depan.",
    },
    {
      hangeul: "기술",
      pelafalan: "gisul",
      arti: "Teknologi",
      contohKalimat: "최신 기술을 활용해 일상 생활을 더 편리하게 만들 수 있어요.",
      pelafalanKalimat: "choesin gisul-eul hwayonghae ilsang saenghwaleul deo pyeonlihage mandeul su iss-eoyo.",
      artiKalimat: "Dengan memanfaatkan teknologi terkini, kita dapat membuat kehidupan sehari-hari lebih nyaman.",
    },
    {
      hangeul: "발전",
      pelafalan: "baljeon",
      arti: "Kemajuan",
      contohKalimat: "국가의 발전에는 교육이 중요한 역할을 합니다.",
      pelafalanKalimat: "guggaui baljeon-eneun gyoyug-i jung-yohan yeoghal-eul habnida.",
      artiKalimat: "Pendidikan memainkan peran penting dalam kemajuan suatu negara.",
    },
    {
      hangeul: "문화",
      pelafalan: "munhwa",
      arti: "Budaya",
      contohKalimat: "한국의 전통 문화를 경험해 보세요.",
      pelafalanKalimat: "hanguk-ui jeontong munhwa-eul gyeongheomhae boseyo.",
      artiKalimat: "Cobalah untuk mengalami budaya tradisional Korea.",
    },
    {
      hangeul: "예술",
      pelafalan: "yesul",
      arti: "Seni",
      contohKalimat: "그녀는 예술에 열정적입니다.",
      pelafalanKalimat: "geunyeoneun yesul-e yeoljeongjeog-imnida.",
      artiKalimat: "Dia sangat bersemangat tentang seni.",
    },
    {
      hangeul: "역사",
      pelafalan: "yeoksa",
      arti: "Sejarah",
      contohKalimat: "우리는 과거의 역사로부터 배워야 합니다.",
      pelafalanKalimat: "ulineun gwageui yeogsalo-buteo baewoya habnida.",
      artiKalimat: "Kita harus belajar dari sejarah masa lalu.",
    },
    {
      hangeul: "과학",
      pelafalan: "gwahag",
      arti: "Ilmu pengetahuan",
      contohKalimat: "과학은 자연 현상을 이해하는 데 도움이 됩니다.",
      pelafalanKalimat: "gwahag-eun jayeon hyeon-sang-eul ihaehaneun de doum-i doedabnida.",
      artiKalimat: "Ilmu pengetahuan membantu memahami fenomena alam.",
    },
    {
      hangeul: "철학",
      pelafalan: "cheolhag",
      arti: "Filsafat",
      contohKalimat: "철학은 존재와 의미에 대해 탐구합니다.",
      pelafalanKalimat: "cheolhag-eun jonjaewa uimi-e daehae tamguhabnida.",
      artiKalimat: "Filsafat mencari makna dan eksistensi.",
    },
    {
      hangeul: "종교",
      pelafalan: "jonggyo",
      arti: "Agama",
      contohKalimat: "다양한 종교가 세계 곳곳에 존재합니다.",
      pelafalanKalimat: "dayanghan jonggyoga segye gosgos-e jogjaehabnida.",
      artiKalimat: "Berbagai agama ada di seluruh penjuru dunia.",
    },
    {
      hangeul: "스포츠",
      pelafalan: "seupocheu",
      arti: "Olahraga",
      contohKalimat: "스포츠는 건강에 좋습니다.",
      pelafalanKalimat: "seupocheuneun geongang-e johseubnida.",
      artiKalimat: "Olahraga baik untuk kesehatan.",
    },
    {
      hangeul: "영화",
      pelafalan: "yeonghwa",
      arti: "Film",
      contohKalimat: "주말에 친구들과 영화를 보러 갈 거예요.",
      pelafalanKalimat: "jumal-e chingudeulgwa yeonghwaleul boleo gal geoyeyo.",
      artiKalimat: "Aku akan pergi menonton film bersama teman-temanku di akhir pekan.",
    },
    {
      hangeul: "음악",
      pelafalan: "eumak",
      arti: "Musik",
      contohKalimat: "음악을 듣는 것은 나를 편안하게 해줍니다.",
      pelafalanKalimat: "eumag-eul deudneun geos-eun naleul pyeon-anhage haejubnida.",
      artiKalimat: "Mendengarkan musik membuat saya merasa nyaman.",
    },
    {
      hangeul: "댄스",
      pelafalan: "daenseu",
      arti: "Tarian",
      contohKalimat: "그녀는 댄스를 잘 추는 편입니다.",
      pelafalanKalimat: "geunyeoneun daenseuleul jal chuneun pyeon-imnida.",
      artiKalimat: "Dia cenderung mahir dalam menari.",
    },
    {
      hangeul: "요리",
      pelafalan: "yoli",
      arti: "Masak",
      contohKalimat: "맛있는 음식을 요리하는 것이 즐겁습니다.",
      pelafalanKalimat: "mas-issneun eumsig-eul yolihaneun geos-i jeulgeobsseubnida.",
      artiKalimat: "Menyajikan makanan lezat adalah menyenangkan.",
    },
    {
      hangeul: "여행",
      pelafalan: "yeohaeng",
      arti: "Perjalanan",
      contohKalimat: "여행은 새로운 경험을 줍니다.",
      pelafalanKalimat: "yeohaeng-eun saeloun gyeongheom-eul jum-nida.",
      artiKalimat: "Perjalanan memberikan pengalaman baru.",
    },
    {
      hangeul: "자연",
      pelafalan: "jayeon",
      arti: "Alam",
      contohKalimat: "자연 속에서 휴식을 취하세요.",
      pelafalanKalimat: "jayeon sog-eseo hyusig-eul chwihaseyo.",
      artiKalimat: "Ambillah istirahat di alam.",
    },
    {
      hangeul: "동물",
      pelafalan: "dongmul",
      arti: "Hewan",
      contohKalimat: "동물들과 소통하는 것은 행복한 경험이에요.",
      pelafalanKalimat: "dongmuldeulgwa sotonghaneun geos-eun haengboghan gyeongheom-ieyo.",
      artiKalimat: "Berinteraksi dengan hewan memberikan pengalaman bahagia.",
    },
    {
      hangeul: "꽃",
      pelafalan: "kkot",
      arti: "Bunga",
      contohKalimat: "봄에는 많은 꽃이 피어납니다.",
      pelafalanKalimat: "bom-eneun manh-eun kkos-i pieonaimnida.",
      artiKalimat: "Banyak bunga mekar di musim semi.",
    },
    {
      hangeul: "사진",
      pelafalan: "sajin",
      arti: "Foto",
      contohKalimat: "여행 사진을 찍는 것을 좋아해요.",
      pelafalanKalimat: "yeohaeng sajin-eul jjig-neun geos-eul johahaeyo.",
      artiKalimat: "Saya suka mengambil foto perjalanan.",
    },
    {
      hangeul: "회화",
      pelafalan: "hoe-hwa",
      arti: "Melukis",
      contohKalimat: "그는 아름다운 회화를 그립니다.",
      pelafalanKalimat: "geuneun aleumdaun hoe-hwaleul geulibnida.",
      artiKalimat: "Dia melukis lukisan indah.",
    },
  ],

  level12: [
    {
      hangeul: "디자인",
      pelafalan: "dijain",
      arti: "Desain",
      contohKalimat: "이 회사의 로고 디자인이 정말 멋있어요.",
      pelafalanKalimat: "i hoesaui rogo dijaini jeongmal meosisseoyo.",
      artiKalimat: "Desain logo perusahaan ini benar-benar keren.",
    },
    {
      hangeul: "건축",
      pelafalan: "geonchuk",
      arti: "Arsitektur",
      contohKalimat: "그 건물의 건축 양식이 독특합니다.",
      pelafalanKalimat: "geu geonmul-ui geonchuk yangsigi dokteukhamnida.",
      artiKalimat: "Gaya arsitektur bangunan itu unik.",
    },
    {
      hangeul: "미용",
      pelafalan: "miyong",
      arti: "Kecantikan",
      contohKalimat: "언니가 미용 관련 일을 합니다.",
      pelafalanKalimat: "eonni-ga miyong gwanlyeon il-eul hamnida.",
      artiKalimat: "Kakak perempuan saya bekerja di bidang kecantikan.",
    },
    {
      hangeul: "패션",
      pelafalan: "paesyeon",
      arti: "Mode/Fashion",
      contohKalimat: "그녀는 유행에 민감해서 항상 패션에 신경을 씁니다.",
      pelafalanKalimat: "geunyeoneun yuhaeng-e min-gamhaeseo hangsang paesyeon-e singyeong-eul sseubnida.",
      artiKalimat: "Dia selalu peduli dengan mode karena dia peka terhadap tren.",
    },
    {
      hangeul: "쇼핑",
      pelafalan: "syoping",
      arti: "Belanja",
      contohKalimat: "오늘은 친구와 함께 쇼핑을 갈 거예요.",
      pelafalanKalimat: "oneul-eun chinguwa hamkke syoping-eul gal geoyeyo.",
      artiKalimat: "Hari ini saya akan pergi berbelanja bersama teman.",
    },
    {
      hangeul: "도서관",
      pelafalan: "doseogwan",
      arti: "Perpustakaan",
      contohKalimat: "내일 도서관에 책을 반납해야 합니다.",
      pelafalanKalimat: "naeil doseogwan-e chaeg-eul bannabhaeya hamnida.",
      artiKalimat: "Besok saya harus mengembalikan buku ke perpustakaan.",
    },
    {
      hangeul: "박물관",
      pelafalan: "bakmulgwan",
      arti: "Museum",
      contohKalimat: "이 도시에는 멋진 박물관이 많이 있어요.",
      pelafalanKalimat: "i dosi-eneun meosjin bakmulgwan-i manhi iss-eoyo.",
      artiKalimat: "Kota ini memiliki banyak museum yang indah.",
    },
    {
      hangeul: "휴가",
      pelafalan: "hyuga",
      arti: "Liburan",
      contohKalimat: "여름에는 휴가로 해외로 여행을 가고 싶어요.",
      pelafalanKalimat: "yeoleum-eneun hyugalo haeoelo yeohaeng-eul gago sip-eoyo.",
      artiKalimat: "Saya ingin pergi berlibur ke luar negeri pada musim panas.",
    },
    {
      hangeul: "축제",
      pelafalan: "chugje",
      arti: "Festival",
      contohKalimat: "이 도시에서 매년 가을 축제가 열립니다.",
      pelafalanKalimat: "i dosieseo maenyeon gaeul chugjega yeollibnida.",
      artiKalimat: "Setiap tahun di kota ini ada festival musim gugur.",
    },
    {
      hangeul: "이벤트",
      pelafalan: "ibenteu",
      arti: "Acara/Event",
      contohKalimat: "다음 주에 큰 이벤트가 있을 예정입니다.",
      pelafalanKalimat: "daeum ju-e keun ibenteuga iss-eul yejeongimnida.",
      artiKalimat: "Ada acara besar yang akan berlangsung minggu depan.",
    },
    {
      hangeul: "회의",
      pelafalan: "hoeui",
      arti: "Rapat",
      contohKalimat: "오늘 오후 회의가 있으니 참석해주세요.",
      pelafalanKalimat: "oneul ohu hoeuiga iss-euni chamsaghaejuseyo.",
      artiKalimat: "Tolong hadir pada rapat sore ini.",
    },
    {
      hangeul: "면접",
      pelafalan: "myeonjeob",
      arti: "Wawancara Kerja",
      contohKalimat: "내일은 회사 면접이 있어요.",
      pelafalanKalimat: "naeil-eun hoesa myeonjeob-i iss-eoyo.",
      artiKalimat: "Besok saya memiliki wawancara kerja di perusahaan.",
    },
    {
      hangeul: "발표",
      pelafalan: "balpyo",
      arti: "Presentasi/Pidato",
      contohKalimat: "그는 항상 자신감 있게 발표를 해요.",
      pelafalanKalimat: "geuneun hangsang jasin-gam issge balpyoleul haeyo.",
      artiKalimat: "Dia selalu memberikan presentasi dengan percaya diri.",
    },
    {
      hangeul: "수상식",
      pelafalan: "susangsik",
      arti: "Acara Pemberian Penghargaan",
      contohKalimat: "올해의 우수 사원을 위한 수상식이 다음 주에 있을 예정입니다.",
      pelafalanKalimat: "olhaeui usu sa-won-eul wihan susangsik-i da-eum ju-e iss-eul yejeongimnida.",
      artiKalimat: "Acara pemberian penghargaan untuk karyawan yang berprestasi akan diadakan minggu depan.",
    },
    {
      hangeul: "격려",
      pelafalan: "gyeoknyeo",
      arti: "Penghiburan/Dorongan",
      contohKalimat: "친구들은 항상 저를 격려해줍니다.",
      pelafalanKalimat: "chingudeul-eun hangsang jeoleul gyeoknyeohaejubnida.",
      artiKalimat: "Teman-teman saya selalu memberi dukungan kepada saya.",
    },
    {
      hangeul: "지원",
      pelafalan: "jiwon",
      arti: "Pendaftaran/Permohonan",
      contohKalimat: "내가 그 회사에 취업을 지원했어요.",
      pelafalanKalimat: "naega geu hoesae chwi-eob-eul jiwonhaess-eoyo.",
      artiKalimat: "Saya telah mendaftar untuk bekerja di perusahaan itu.",
    },
    {
      hangeul: "헌신",
      pelafalan: "heonsin",
      arti: "Pengabdian",
      contohKalimat: "그는 이 회사에 많은 헌신을 했습니다.",
      pelafalanKalimat: "geuneun i hoesae manh-eun heonsin-eul haessseubnida.",
      artiKalimat: "Dia telah banyak berdedikasi untuk perusahaan ini.",
    },
    {
      hangeul: "협력",
      pelafalan: "hyeoblyeog",
      arti: "Kerjasama",
      contohKalimat: "우리는 팀원들과 좋은 협력을 유지해요.",
      pelafalanKalimat: "uli-neun tim-wondeul-gwa joh-eun hyeoblyeog-eul yujihaeyo.",
      artiKalimat: "Kami menjaga kerjasama yang baik dengan rekan tim kami.",
    },
    {
      hangeul: "경쟁",
      pelafalan: "gyeongjaeng",
      arti: "Persaingan",
      contohKalimat: "시장에서는 무리한 경쟁이 있을 수 있어요.",
      pelafalanKalimat: "sijang-eseoneun mulihan gyeongjaeng-i iss-eul su iss-eoyo.",
      artiKalimat: "Di pasar, mungkin ada persaingan yang ketat.",
    },
    {
      hangeul: "의사소통",
      pelafalan: "uisasotong",
      arti: "Komunikasi",
      contohKalimat: "효과적인 의사소통이 중요합니다.",
      pelafalanKalimat: "hyogwahageun uisasotong-i jung-yohabnikka.",
      artiKalimat: "Komunikasi yang efektif sangat penting.",
    },
  ],
};
